name: Windows build

# NOT WORKING

on:
  # push
  # pull_request
  workflow_dispatch

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        perl:
          - '5.42'
          - '5.40'
          - '5.38'
          - '5.36'
          - '5.34'
          - '5.32'
          # - '5.30'
          # - '5.28'
          # - '5.26'
          # - '5.24'
          # - '5.22'
          # - '5.20'
          # - '5.18'
          # - '5.16'
          # - '5.14'
          # - '5.12'
          # - '5.10'
          # - '5.8'

    name: Perl ${{ matrix.perl }}
    steps:
    - uses: actions/checkout@v4
    - name: Setup perl
      uses: shogo82148/actions-setup-perl@v1
      with:
        perl-version: ${{ matrix.perl }}
    - name: Perl version
      run: perl -V
    # Install liblzma on windows
    - name: Install liblzma
      run: vcpkg install liblzma:x64-windows
    - name: Install dependencies
      run: cpanm --quiet --installdeps --notest .
    - name: Build
      run: perl Makefile.PL && make
      env:
        LIBLZMA_INCLUDE: C:\vcpkg\installed\x64-windows\include
        LIBLZMA_LIB: C:\vcpkg\installed\x64-windows\lib
    - name: Test
      run: make test
      env:
        LIBLZMA_INCLUDE: C:\vcpkg\installed\x64-windows\include
        LIBLZMA_LIB: C:\vcpkg\installed\x64-windows\lib
